"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { QUESTIONS, type QuizAnswers } from "@/lib/curation/questions";
import { HEART_SRC } from "@/lib/asset";
import { recommendedVersionAcrossLoaders, recommendedLoader, bestLoaderCount, sizeOptionsFor, type Coverage } from "@/lib/catalog/coverage";
import snapshotCoverage from "@/lib/catalog/coverage.snapshot.json";
import type { Loader } from "@/lib/sources/types";

const ANSWERS_KEY = "fullhearts:answers";
const PROGRESS_KEY = "fullhearts:progress";

interface SavedProgress {
  step: number;
  answers: QuizAnswers;
}

const HEART = (
  <img
    src={HEART_SRC}
    alt=""
    aria-hidden="true"
    style={{ width: "100%", height: "100%", display: "block", imageRendering: "pixelated" }}
  />
);

export default function Quiz() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<QuizAnswers>({});
  const [resume, setResume] = useState<SavedProgress | null>(null);
  const hydrated = useRef(false);

  // Per-build mod counts per loader+version (real, not the project-level union
  // that falsely inflated e.g. Forge 1.21.1). Committed snapshot, regenerated by
  // scripts/gen-coverage.mjs. Drives the recommended-version steer + the counts shown.
  const coverage = snapshotCoverage as Coverage;

  // On mount, surface any in-progress quiz as a resume offer (don't auto-apply).
  useEffect(() => {
    try {
      const raw = sessionStorage.getItem(PROGRESS_KEY);
      if (raw) {
        const saved = JSON.parse(raw) as SavedProgress;
        if (saved && (saved.step > 0 || Object.keys(saved.answers ?? {}).length > 0)) {
          setResume(saved);
        }
      }
    } catch {
      // sessionStorage unavailable — just start fresh.
    }
    hydrated.current = true;
  }, []);

  // Persist progress after hydration so a reload/return can resume.
  useEffect(() => {
    if (!hydrated.current) return;
    try {
      sessionStorage.setItem(PROGRESS_KEY, JSON.stringify({ step, answers }));
    } catch {
      // ignore — resume is best-effort.
    }
  }, [step, answers]);

  const applyResume = useCallback(() => {
    if (!resume) return;
    setStep(resume.step);
    setAnswers(resume.answers);
    setResume(null);
  }, [resume]);

  const startOver = useCallback(() => {
    setResume(null);
    setStep(0);
    setAnswers({});
    try {
      sessionStorage.removeItem(PROGRESS_KEY);
    } catch {
      // ignore
    }
  }, []);

  const question = QUESTIONS[step];
  const total = QUESTIONS.length;
  const selected = answers[question.id] ?? [];
  const progress = Math.round((step / total) * 100);
  const canAdvance = selected.length > 0;

  // Map quiz answers -> chosen loader/version (loader option ids equal loader names).
  const chosenLoader = (answers.loader?.[0] ?? "forge") as Loader;
  const versionById: Record<string, string> = {};
  for (const o of QUESTIONS.find((q) => q.id === "version")?.options ?? []) {
    if (o.gameVersion) versionById[o.id] = o.gameVersion;
  }
  const chosenVersion = versionById[answers.version?.[0] ?? ""] ?? "1.20.1";

  // Decorate the version, loader and size steps with real availability. Version is
  // asked before the loader, so it shows each version's BEST-loader potential and
  // recommends the best version overall; the loader step then shows per-loader
  // counts for the chosen version and recommends the one with the most mods.
  type DisplayOption = { id: string; label: string; note?: string; recommended?: boolean };
  let displayOptions: DisplayOption[];
  if (question.id === "version") {
    const recV = recommendedVersionAcrossLoaders(coverage);
    const withCounts = question.options.map((o) => ({
      id: o.id,
      label: o.label,
      count: bestLoaderCount(coverage, o.gameVersion ?? ""),
      gameVersion: o.gameVersion
    }));
    const MIN = 8;
    const enough = withCounts.filter((o) => o.count >= MIN);
    const some = withCounts.filter((o) => o.count > 0);
    const shown = enough.length > 0 ? enough : some.length > 0 ? some : withCounts;
    displayOptions = shown.map((o) => ({
      id: o.id,
      label: o.label,
      note: `${o.count} mods`,
      recommended: o.gameVersion === recV
    }));
  } else if (question.id === "loader") {
    const recL = recommendedLoader(coverage, chosenVersion);
    displayOptions = question.options.map((o) => ({
      id: o.id,
      label: o.label,
      note: `${coverage[o.id as Loader]?.[chosenVersion] ?? 0} mods`,
      recommended: o.id === recL
    }));
  } else if (question.id === "size") {
    const count = coverage[chosenLoader]?.[chosenVersion] ?? 0;
    displayOptions = sizeOptionsFor(count).map((o) => ({
      id: o.id,
      label: o.label,
      recommended: o.recommended
    }));
  } else {
    displayOptions = question.options.map((o) => ({ id: o.id, label: o.label }));
  }

  const toggle = useCallback(
    (optionId: string) => {
      setAnswers((prev) => {
        const current = prev[question.id] ?? [];
        if (question.kind === "single") {
          return { ...prev, [question.id]: [optionId] };
        }
        const opts = question.options;
        const toggled = opts.find((o) => o.id === optionId);
        const exclusiveIds = new Set(opts.filter((o) => o.exclusive).map((o) => o.id));
        // Turning ON an exclusive option replaces the whole answer with just it.
        if (toggled?.exclusive && !current.includes(optionId)) {
          return { ...prev, [question.id]: [optionId] };
        }
        let next = current.includes(optionId)
          ? current.filter((id) => id !== optionId)
          : [...current, optionId];
        // Turning ON a normal option drops any selected exclusive option.
        if (!toggled?.exclusive && !current.includes(optionId)) {
          next = next.filter((id) => !exclusiveIds.has(id));
        }
        return { ...prev, [question.id]: next };
      });
    },
    [question]
  );

  const finish = useCallback(
    (final: QuizAnswers) => {
      try {
        sessionStorage.setItem(ANSWERS_KEY, JSON.stringify(final));
        sessionStorage.removeItem(PROGRESS_KEY); // quiz is complete; nothing to resume
      } catch {
        // sessionStorage may be unavailable (private mode); results page falls back.
      }
      router.push("/results");
    },
    [router]
  );

  const next = useCallback(() => {
    if (!canAdvance) return;
    if (step < total - 1) setStep((s) => s + 1);
    else finish(answers);
  }, [canAdvance, step, total, finish, answers]);

  const back = useCallback(() => {
    if (step > 0) setStep((s) => s - 1);
  }, [step]);

  // Keyboard: number keys pick options, Enter advances, Backspace goes back.
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (resume) return; // resume offer is up — let the user choose first
      if (e.key === "Enter") {
        next();
      } else if (e.key === "Backspace") {
        e.preventDefault();
        back();
      } else {
        const n = Number(e.key);
        if (Number.isInteger(n) && n >= 1 && n <= displayOptions.length) {
          toggle(displayOptions[n - 1].id);
        }
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [next, back, toggle, displayOptions, resume]);

  return (
    <>
      <header className="nav">
        <div className="nav-inner">
          <Link className="brand" href="/" style={{ textDecoration: "none" }}>
            <span className="heart" style={{ width: 26, height: 26, display: "inline-flex" }}>{HEART}</span>
            <span className="name">FULL<b>HEARTS</b></span>
          </Link>
          <Link className="nav-cta" href="/">Exit</Link>
        </div>
      </header>

      <main className="quiz">
        {resume && (
          <div className="resume-banner" role="alert">
            <div>
              <strong>Pick up where you left off?</strong>
              <span> You were on question {resume.step + 1} of {total}.</span>
            </div>
            <div className="resume-actions">
              <button type="button" className="btn-primary" onClick={applyResume}>Resume</button>
              <button type="button" className="btn-ghost" onClick={startOver}>Start over</button>
            </div>
          </div>
        )}

        <div className="quiz-progress" aria-hidden="true"><i style={{ width: `${progress}%` }} /></div>
        <div className="quiz-step">QUESTION {step + 1} / {total}</div>

        <h2>{question.prompt}</h2>
        {question.help && <p className="help">{question.help}</p>}
        {question.id === "loader" && (
          <p className="help">
            For Minecraft {chosenVersion}, {recommendedLoader(coverage, chosenVersion) === "neoforge" ? "NeoForge" : recommendedLoader(coverage, chosenVersion).charAt(0).toUpperCase() + recommendedLoader(coverage, chosenVersion).slice(1)} has the most mods.
          </p>
        )}

        <div className="quiz-options" role={question.kind === "single" ? "radiogroup" : "group"}>
          {displayOptions.map((opt, i) => {
            const isSel = selected.includes(opt.id);
            return (
              <button
                key={opt.id}
                type="button"
                className={`quiz-option${isSel ? " selected" : ""}`}
                aria-pressed={isSel}
                onClick={() => toggle(opt.id)}
              >
                <span className="key">{i + 1}</span>
                <span className="quiz-option-label">{opt.label}</span>
                {opt.recommended && <span className="quiz-tag">Recommended</span>}
                {opt.note && <span className="quiz-note">{opt.note}</span>}
              </button>
            );
          })}
        </div>

        <div className="quiz-nav">
          <button type="button" className={`btn-ghost${step === 0 ? " btn-disabled" : ""}`} onClick={back}>Back</button>
          <span className="spacer" />
          <button type="button" className={`btn-primary${canAdvance ? "" : " btn-disabled"}`} onClick={next}>
            {step < total - 1 ? "Next" : "See my loadout"}
          </button>
        </div>
      </main>
    </>
  );
}
