import type { CuratedMod } from "@/lib/sources/types";

/**
 * Curated seed catalog. Tag affinities are 0..1 (how strongly a mod serves a
 * preference). `reasonTemplate` is rendered to the "why" line in Plan 2.
 * `modrinthSlug` is the slug in modrinth.com/mod/<slug>.
 */
export const CATALOG: CuratedMod[] = [
  {
    id: "sodium",
    name: "Sodium",
    summary: "Rebuilds the rendering engine for big FPS gains with no visual downsides.",
    curatedTags: { performance: 1 },
    reasonTemplate: "you wanted better performance",
    modrinthSlug: "sodium"
  },
  {
    id: "lithium",
    name: "Lithium",
    summary: "Optimizes tick logic, mob AI, and physics without changing behavior.",
    curatedTags: { performance: 0.9 },
    reasonTemplate: "you wanted smoother performance",
    modrinthSlug: "lithium"
  },
  {
    id: "ferritecore",
    name: "FerriteCore",
    summary: "Cuts memory usage by storing block and chunk data more efficiently.",
    curatedTags: { performance: 0.7 },
    reasonTemplate: "you're on limited hardware",
    modrinthSlug: "ferrite-core"
  },
  {
    id: "iris",
    name: "Iris Shaders",
    summary: "Runs shader packs while staying compatible with Sodium.",
    curatedTags: { visual: 1, performance: 0.4 },
    reasonTemplate: "you wanted better visuals",
    modrinthSlug: "iris"
  },
  {
    id: "modmenu",
    name: "Mod Menu",
    summary: "Adds a clean in-game screen to configure every Fabric mod you have.",
    curatedTags: { interface: 0.9 },
    reasonTemplate: "you wanted easy configuration",
    modrinthSlug: "modmenu"
  },
  {
    id: "jade",
    name: "Jade",
    summary: "Shows what you're looking at (block name, mod, mob health) in a tooltip.",
    curatedTags: { interface: 0.8, exploration: 0.3 },
    reasonTemplate: "you wanted clearer in-game info",
    modrinthSlug: "jade"
  },
  {
    id: "jei",
    name: "Just Enough Items (JEI)",
    summary: "Look up the recipe or usage of any item from your inventory.",
    curatedTags: { interface: 1, tech: 0.4, automation: 0.3 },
    reasonTemplate: "you wanted recipe lookups",
    modrinthSlug: "jei"
  },
  {
    id: "appleskin",
    name: "AppleSkin",
    summary: "Reveals exactly how much hunger and saturation food restores.",
    curatedTags: { interface: 0.6 },
    reasonTemplate: "you wanted clearer survival info",
    modrinthSlug: "appleskin"
  },
  {
    id: "xaeros-minimap",
    name: "Xaero's Minimap",
    summary: "A corner minimap with waypoints, cave mode, and mob radar.",
    curatedTags: { exploration: 1, interface: 0.5 },
    reasonTemplate: "you love to explore",
    modrinthSlug: "xaeros-minimap"
  },
  {
    id: "create",
    name: "Create",
    summary: "Build rotating, moving machines like windmills, conveyors, even trains.",
    curatedTags: { tech: 1, automation: 1, building: 0.5, "low-grind": 0.6 },
    reasonTemplate: "you wanted mechanical automation",
    modrinthSlug: "create-fabric"
  },
  {
    id: "botania",
    name: "Botania",
    summary: "Magic generated by living flowers and mana, with deep build-driven systems.",
    curatedTags: { magic: 1, automation: 0.6, building: 0.4, "low-grind": 0.7 },
    reasonTemplate: "you wanted magic without the grind",
    modrinthSlug: "botania"
  },
  {
    id: "ars-nouveau",
    name: "Ars Nouveau",
    summary: "Combine glyphs to design custom spells and automate them.",
    curatedTags: { magic: 1, automation: 0.5, rpg: 0.4 },
    reasonTemplate: "you wanted creative spellcrafting",
    modrinthSlug: "ars-nouveau"
  },
  {
    id: "farmers-delight-refabricated",
    name: "Farmer's Delight",
    summary: "A cozy cooking system with new crops, tools, and meals.",
    curatedTags: { "low-grind": 0.8, building: 0.3, rpg: 0.3 },
    reasonTemplate: "you wanted cozy, low-pressure content",
    modrinthSlug: "farmers-delight-refabricated"
  },
  {
    id: "terralith",
    name: "Terralith",
    summary: "Reworks generation into dramatic, believable landscapes using vanilla blocks.",
    curatedTags: { exploration: 1, visual: 0.6 },
    reasonTemplate: "you wanted more to explore",
    modrinthSlug: "terralith"
  },
  {
    id: "supplementaries",
    name: "Supplementaries",
    summary: "Sconces, signs, urns, and dozens of tasteful props that make spaces feel lived-in.",
    curatedTags: { building: 1, "low-grind": 0.5 },
    reasonTemplate: "you love building and decorating",
    modrinthSlug: "supplementaries"
  },
  {
    id: "macaws-furniture",
    name: "Macaw's Furniture",
    summary: "Furniture, roofs, bridges, doors, and windows for pure building range.",
    curatedTags: { building: 1 },
    reasonTemplate: "you love building and decorating",
    modrinthSlug: "macaws-furniture"
  },
  {
    id: "alexs-mobs",
    name: "Alex's Mobs",
    summary: "Over 100 distinctive ambient creatures across oceans, skies, and biomes.",
    curatedTags: { exploration: 0.7, combat: 0.5, rpg: 0.4 },
    reasonTemplate: "you wanted a more alive world",
    modrinthSlug: "alexs-mobs"
  },
  {
    id: "cataclysm",
    name: "L_Ender's Cataclysm",
    summary: "Serious, fair boss fights tucked inside themed dungeons.",
    curatedTags: { combat: 1, exploration: 0.6, rpg: 0.5 },
    reasonTemplate: "you wanted tougher combat",
    modrinthSlug: "lenders-cataclysm"
  },
  {
    id: "open-parties-claims",
    name: "Open Parties and Claims",
    summary: "Claim your land so mobs and friends can't wreck it, and form parties.",
    curatedTags: { coop: 1, building: 0.3 },
    reasonTemplate: "you play with friends",
    modrinthSlug: "open-parties-and-claims"
  },
  {
    id: "sodium-extra",
    name: "Sodium Extra",
    summary: "Extra video-setting toggles on top of Sodium for fine performance tuning.",
    curatedTags: { performance: 0.7, interface: 0.4 },
    reasonTemplate: "you wanted more performance control",
    modrinthSlug: "sodium-extra"
  },
  {
  id: "crispy",
  name: "Crispy!",
  summary: "Remakes Minecraft cookies with dozens of new crunchy cookie types.",
  curatedTags: { food: 1, visual: 0.4 },
  reasonTemplate: "you wanted a crispy cookie expansion",
  modrinthSlug: "crispy!"
  },
  {
    id: "emi",
    name: "EMI",
    summary: "A fast, modern item and recipe viewer with crafting trees and favorites.",
    curatedTags: { interface: 1, qol: 0.6 },
    reasonTemplate: "you wanted easy recipe lookups",
    modrinthSlug: "emi"
  },
  {
    id: "mouse-tweaks",
    name: "Mouse Tweaks",
    summary: "Smarter inventory dragging and item moving with the mouse.",
    curatedTags: { qol: 1, interface: 0.4 },
    reasonTemplate: "you wanted smoother inventory handling",
    modrinthSlug: "mouse-tweaks"
  },
  {
    id: "carry-on",
    name: "Carry On",
    summary: "Pick up and carry chests, machines, and mobs without breaking them.",
    curatedTags: { qol: 1, building: 0.4 },
    reasonTemplate: "you wanted easier hauling",
    modrinthSlug: "carry-on"
  },
  {
    id: "betterf3",
    name: "BetterF3",
    summary: "A clean, configurable replacement for the F3 debug screen.",
    curatedTags: { interface: 1 },
    reasonTemplate: "you wanted clearer on-screen info",
    modrinthSlug: "betterf3"
  },
  {
    id: "continuity",
    name: "Continuity",
    summary: "Connected textures done right, fully compatible with Sodium.",
    curatedTags: { visual: 1 },
    reasonTemplate: "you wanted nicer-looking blocks",
    modrinthSlug: "continuity"
  },
  {
    id: "modernfix",
    name: "ModernFix",
    summary: "Faster load times and lower memory use, stacks with other optimizers.",
    curatedTags: { performance: 1 },
    reasonTemplate: "you wanted faster loading and less RAM use",
    modrinthSlug: "modernfix"
  },
  {
    id: "not-enough-animations",
    name: "Not Enough Animations",
    summary: "Adds third-person animations for drinking, eating, climbing, and more.",
    curatedTags: { visual: 1 },
    reasonTemplate: "you wanted livelier player animations",
    modrinthSlug: "not-enough-animations"
  },
  {
    id: "3dskinlayers",
    name: "3D Skin Layers",
    summary: "Renders your skin's outer layer in 3D for a less flat look.",
    curatedTags: { visual: 0.9 },
    reasonTemplate: "you wanted a better-looking character",
    modrinthSlug: "3dskinlayers"
  },
  {
    id: "cobblemon",
    name: "Cobblemon",
    summary: "A polished, open-source Pokemon mod with capture, training, and battles.",
    curatedTags: { rpg: 1, mobs: 0.8, exploration: 0.5 },
    reasonTemplate: "you wanted creature collecting and battling",
    modrinthSlug: "cobblemon"
  },
  {
    id: "naturalist",
    name: "Naturalist",
    summary: "Realistic ambient wildlife: bears, deer, snakes, fireflies, and more.",
    curatedTags: { mobs: 1, exploration: 0.4 },
    reasonTemplate: "you wanted a more alive world",
    modrinthSlug: "naturalist"
  },
  {
    id: "friends-and-foes",
    name: "Friends & Foes",
    summary: "Adds the mobs Mojang showed but never shipped, faithfully done.",
    curatedTags: { mobs: 1 },
    reasonTemplate: "you wanted more creatures",
    modrinthSlug: "friends-and-foes"
  },
  {
    id: "creeper-overhaul",
    name: "Creeper Overhaul",
    summary: "Biome-specific creeper variants that look great and fit the world.",
    curatedTags: { mobs: 1, visual: 0.4 },
    reasonTemplate: "you wanted more characterful mobs",
    modrinthSlug: "creeper-overhaul"
  },
  {
    id: "deeperdarker",
    name: "Deeper and Darker",
    summary: "Expands the Deep Dark with a new dimension, gear, and a boss.",
    curatedTags: { exploration: 1, combat: 0.6, structures: 0.5 },
    reasonTemplate: "you wanted more to explore underground",
    modrinthSlug: "deeperdarker"
  },
  {
    id: "waystones",
    name: "Waystones",
    summary: "Place waystones and fast-travel between them across your world.",
    curatedTags: { qol: 1, exploration: 0.5 },
    reasonTemplate: "you wanted convenient fast travel",
    modrinthSlug: "waystones"
  },
  {
    id: "natures-compass",
    name: "Nature's Compass",
    summary: "Search for and locate any biome from a simple interface.",
    curatedTags: { interface: 0.9, exploration: 0.7 },
    reasonTemplate: "you wanted to find biomes easily",
    modrinthSlug: "natures-compass"
  },
  {
    id: "explorers-compass",
    name: "Explorer's Compass",
    summary: "Locate any structure in your world and track it down.",
    curatedTags: { interface: 0.9, exploration: 0.7, structures: 0.5 },
    reasonTemplate: "you wanted to find structures easily",
    modrinthSlug: "explorers-compass"
  },
  {
    id: "travelersbackpack",
    name: "Traveler's Backpack",
    summary: "Wearable backpacks with big storage, tanks, and crafting on the go.",
    curatedTags: { qol: 1, exploration: 0.4 },
    reasonTemplate: "you wanted more storage on the move",
    modrinthSlug: "travelersbackpack"
  },
  {
    id: "yungs-better-dungeons",
    name: "YUNG's Better Dungeons",
    summary: "Reworks vanilla dungeons into large, rewarding hand-built encounters.",
    curatedTags: { structures: 1, exploration: 0.6, combat: 0.4 },
    reasonTemplate: "you wanted better places to explore",
    modrinthSlug: "yungs-better-dungeons"
  },
  {
    id: "dungeons-and-taverns",
    name: "Dungeons and Taverns",
    summary: "Adds varied new structures and overhauls strongholds, datapack-light.",
    curatedTags: { structures: 1, exploration: 0.6 },
    reasonTemplate: "you wanted richer world structures",
    modrinthSlug: "dungeons-and-taverns"
  },
  {
    id: "better-combat",
    name: "Better Combat",
    summary: "Souls-like melee with combos, reach, and weapon-specific attacks.",
    curatedTags: { combat: 1, rpg: 0.4 },
    reasonTemplate: "you wanted deeper, snappier combat",
    modrinthSlug: "better-combat"
  },
  {
    id: "simply-swords",
    name: "Simply Swords",
    summary: "A big set of new weapon types with unique abilities and effects.",
    curatedTags: { combat: 1, rpg: 0.5 },
    reasonTemplate: "you wanted more weapon variety",
    modrinthSlug: "simply-swords"
  },
  {
    id: "immersive-armors",
    name: "Immersive Armors",
    summary: "Many balanced new armor sets, each with a useful set bonus.",
    curatedTags: { combat: 0.8, rpg: 0.5 },
    reasonTemplate: "you wanted more armor options",
    modrinthSlug: "immersive-armors"
  },
  {
    id: "biomes-o-plenty",
    name: "Biomes O' Plenty",
    summary: "Dozens of beautiful new biomes, blocks, and plants for overworld variety.",
    curatedTags: { biome: 1, exploration: 0.6, visual: 0.4 },
    reasonTemplate: "you wanted a richer overworld",
    modrinthSlug: "biomes-o-plenty"
  },
  {
    id: "biomeswevegone",
    name: "Oh The Biomes We've Gone",
    summary: "A massive biome expansion with new trees, terrain, and atmosphere.",
    curatedTags: { biome: 1, exploration: 0.6 },
    reasonTemplate: "you wanted far more biomes to find",
    modrinthSlug: "oh-the-biomes-weve-gone"
  },
  {
    id: "natures-spirit",
    name: "Nature's Spirit",
    summary: "Gorgeous new biomes, wood types, and decorative blocks.",
    curatedTags: { biome: 1, building: 0.5, visual: 0.4 },
    reasonTemplate: "you wanted prettier, more varied nature",
    modrinthSlug: "natures-spirit"
  },
  {
    id: "lets-do-vinery",
    name: "[Let's Do] Vinery",
    summary: "Grow grapes and craft wine with cozy winemaking blocks and decor.",
    curatedTags: { food: 1, building: 0.5, "low-grind": 0.5 },
    reasonTemplate: "you wanted cozy farming and crafting",
    modrinthSlug: "lets-do-vinery"
  },
  {
    id: "rightclickharvest",
    name: "RightClickHarvest",
    summary: "Harvest and replant crops with a single right-click.",
    curatedTags: { qol: 1, food: 0.5 },
    reasonTemplate: "you wanted easier farming",
    modrinthSlug: "rightclickharvest"
  },
  {
    id: "bountiful",
    name: "Bountiful",
    summary: "A bounty board that hands out fetch and hunt quests for rewards.",
    curatedTags: { rpg: 0.8, exploration: 0.4 },
    reasonTemplate: "you wanted goals and progression",
    modrinthSlug: "bountiful"
  },
  {
    id: "villager-trading-plus",
    name: "Villager Trading Plus",
    summary: "Expands villager trades with more useful, balanced offers.",
    curatedTags: { qol: 0.8, rpg: 0.3 },
    reasonTemplate: "you wanted better villager trading",
    modrinthSlug: "trading+"
  },
  {
    id: "enchantment-descriptions",
    name: "Enchantment Descriptions",
    summary: "Shows what each enchantment actually does, right in the tooltip.",
    curatedTags: { interface: 1, magic: 0.4 },
    reasonTemplate: "you wanted clearer enchantment info",
    modrinthSlug: "enchantment-descriptions"
  },
  {
    id: "immersive-aircraft",
    name: "Immersive Aircraft",
    summary: "Hand-crafted planes, airships, and gyrocopters for getting around.",
    curatedTags: { tech: 0.8, exploration: 0.6 },
    reasonTemplate: "you wanted new ways to travel",
    modrinthSlug: "immersive-aircraft"
  },
  {
    id: "create-forge",
    name: "Create",
    summary: "Build rotating contraptions, machines, and automated factories with style.",
    curatedTags: { tech: 1, automation: 1, building: 0.5 },
    reasonTemplate: "you wanted mechanical automation",
    modrinthSlug: "create"
  },
  {
    id: "cc-tweaked",
    name: "CC: Tweaked",
    summary: "Programmable in-game computers and robots you script with Lua.",
    curatedTags: { tech: 1, automation: 0.6 },
    reasonTemplate: "you like engineering and automation",
    modrinthSlug: "cc-tweaked"
  },
  {
    id: "advanced-peripherals",
    name: "Advanced Peripherals",
    summary: "Extends CC: Tweaked computers with blocks that interact with the world.",
    curatedTags: { tech: 1, automation: 0.7 },
    reasonTemplate: "you like deep tech systems",
    modrinthSlug: "advancedperipherals"
  },
  {
    id: "farmers-delight",
    name: "Farmer's Delight",
    summary: "Cooking, crops, and kitchen tools for a richer farm-to-table loop.",
    curatedTags: { food: 1, "low-grind": 0.4 },
    reasonTemplate: "you wanted cozy farming and cooking",
    modrinthSlug: "farmers-delight"
  },
  {
    id: "lets-do-bakery",
    name: "Let's Do: Bakery",
    summary: "Baking stations, breads, and shop counters for cozy cafes.",
    curatedTags: { food: 1, building: 0.3 },
    reasonTemplate: "you wanted cooking and decoration",
    modrinthSlug: "lets-do-bakery"
  },
  {
    id: "comforts",
    name: "Comforts",
    summary: "Sleeping bags and hammocks so you can rest without setting spawn.",
    curatedTags: { qol: 0.8, "low-grind": 0.3 },
    reasonTemplate: "you wanted quality-of-life travel comfort",
    modrinthSlug: "comforts"
  },
  {
    id: "patchouli",
    name: "Patchouli",
    summary: "Powers in-game guidebooks and tutorials used by many content mods.",
    curatedTags: { interface: 0.7, qol: 0.5 },
    reasonTemplate: "you wanted in-game guides",
    modrinthSlug: "patchouli"
  },
  {
    id: "xaeros-world-map",
    name: "Xaero's World Map",
    summary: "Full-screen self-writing world map that pairs with the minimap.",
    curatedTags: { interface: 1, exploration: 0.4 },
    reasonTemplate: "you wanted maps and navigation",
    modrinthSlug: "xaeros-world-map"
  },
  {
    id: "lightmans-currency",
    name: "Lightman's Currency",
    summary: "Coins, ATMs, and player-run shops for server economies.",
    curatedTags: { coop: 0.7, qol: 0.5, interface: 0.3 },
    reasonTemplate: "you play with friends or on servers",
    modrinthSlug: "lightmans-currency"
  },
  {
    id: "learnplay",
    name: "LearnPlay",
    summary: "Educational flashcard pop-ups that turn play into light learning.",
    curatedTags: { interface: 0.6, qol: 0.4 },
    reasonTemplate: "you wanted a learning-friendly twist",
    modrinthSlug: "learnplay"
  }
];
