import type { CuratedMod } from "@/lib/sources/types";

/**
 * Curated seed catalog. Tag affinities are 0..1 (how strongly a mod serves a
 * preference). `reasonTemplate` is rendered to the "why" line in Plan 2.
 * `modrinthSlug` is the slug in modrinth.com/mod/<slug>.
 */
export const CATALOG: CuratedMod[] = [
  {
    id: "sodium",
    name: "Sodium",
    summary: "Rebuilds the rendering engine for big FPS gains with no visual downsides.",
    curatedTags: { performance: 1, "low-end": 1 },
    reasonTemplate: "you wanted better performance",
    modrinthSlug: "sodium"
  },
  {
    id: "lithium",
    name: "Lithium",
    summary: "Optimizes tick logic, mob AI, and physics without changing behavior.",
    curatedTags: { performance: 0.9, "low-end": 0.8 },
    reasonTemplate: "you wanted smoother performance",
    modrinthSlug: "lithium"
  },
  {
    id: "ferritecore",
    name: "FerriteCore",
    summary: "Cuts memory usage by storing block and chunk data more efficiently.",
    curatedTags: { performance: 0.7, "low-end": 0.9 },
    reasonTemplate: "you're on limited hardware",
    modrinthSlug: "ferrite-core"
  },
  {
    id: "iris",
    name: "Iris Shaders",
    summary: "Runs shader packs while staying compatible with Sodium.",
    curatedTags: { visual: 1, performance: 0.4 },
    reasonTemplate: "you wanted better visuals",
    modrinthSlug: "iris"
  },
  {
    id: "modmenu",
    name: "Mod Menu",
    summary: "Adds a clean in-game screen to configure every Fabric mod you have.",
    curatedTags: { interface: 0.9 },
    reasonTemplate: "you wanted easy configuration",
    modrinthSlug: "modmenu"
  },
  {
    id: "jade",
    name: "Jade",
    summary: "Shows what you're looking at — block name, mod, mob health — in a tooltip.",
    curatedTags: { interface: 0.8, exploration: 0.3 },
    reasonTemplate: "you wanted clearer in-game info",
    modrinthSlug: "jade"
  },
  {
    id: "jei",
    name: "Just Enough Items (JEI)",
    summary: "Look up the recipe or usage of any item from your inventory.",
    curatedTags: { interface: 1, tech: 0.4, automation: 0.3 },
    reasonTemplate: "you wanted recipe lookups",
    modrinthSlug: "jei"
  },
  {
    id: "appleskin",
    name: "AppleSkin",
    summary: "Reveals exactly how much hunger and saturation food restores.",
    curatedTags: { interface: 0.6 },
    reasonTemplate: "you wanted clearer survival info",
    modrinthSlug: "appleskin"
  },
  {
    id: "xaeros-minimap",
    name: "Xaero's Minimap",
    summary: "A corner minimap with waypoints, cave mode, and mob radar.",
    curatedTags: { exploration: 1, interface: 0.5 },
    reasonTemplate: "you love to explore",
    modrinthSlug: "xaeros-minimap"
  },
  {
    id: "create",
    name: "Create",
    summary: "Build rotating, moving machines — windmills, conveyors, even trains.",
    curatedTags: { tech: 1, automation: 1, building: 0.5, "low-grind": 0.6 },
    reasonTemplate: "you wanted mechanical automation",
    modrinthSlug: "create-fabric"
  },
  {
    id: "botania",
    name: "Botania",
    summary: "Magic generated by living flowers and mana, with deep build-driven systems.",
    curatedTags: { magic: 1, automation: 0.6, building: 0.4, "low-grind": 0.7 },
    reasonTemplate: "you wanted magic without the grind",
    modrinthSlug: "botania"
  },
  {
    id: "ars-nouveau",
    name: "Ars Nouveau",
    summary: "Combine glyphs to design custom spells and automate them.",
    curatedTags: { magic: 1, automation: 0.5, rpg: 0.4 },
    reasonTemplate: "you wanted creative spellcrafting",
    modrinthSlug: "ars-nouveau"
  },
  {
    id: "farmers-delight",
    name: "Farmer's Delight",
    summary: "A cozy cooking system with new crops, tools, and meals.",
    curatedTags: { "low-grind": 0.8, building: 0.3, rpg: 0.3 },
    reasonTemplate: "you wanted cozy, low-pressure content",
    modrinthSlug: "farmers-delight"
  },
  {
    id: "terralith",
    name: "Terralith",
    summary: "Reworks generation into dramatic, believable landscapes using vanilla blocks.",
    curatedTags: { exploration: 1, visual: 0.6 },
    reasonTemplate: "you wanted more to explore",
    modrinthSlug: "terralith"
  },
  {
    id: "supplementaries",
    name: "Supplementaries",
    summary: "Sconces, signs, urns, and dozens of tasteful props that make spaces feel lived-in.",
    curatedTags: { building: 1, "low-grind": 0.5 },
    reasonTemplate: "you love building and decorating",
    modrinthSlug: "supplementaries"
  },
  {
    id: "macaws-furniture",
    name: "Macaw's Furniture",
    summary: "Furniture, roofs, bridges, doors, and windows — pure building range.",
    curatedTags: { building: 1 },
    reasonTemplate: "you love building and decorating",
    modrinthSlug: "macaws-furniture"
  },
  {
    id: "alexs-mobs",
    name: "Alex's Mobs",
    summary: "Over 100 distinctive ambient creatures across oceans, skies, and biomes.",
    curatedTags: { exploration: 0.7, combat: 0.5, rpg: 0.4 },
    reasonTemplate: "you wanted a more alive world",
    modrinthSlug: "alexs-mobs"
  },
  {
    id: "cataclysm",
    name: "L_Ender's Cataclysm",
    summary: "Serious, fair boss fights tucked inside themed dungeons.",
    curatedTags: { combat: 1, exploration: 0.6, rpg: 0.5 },
    reasonTemplate: "you wanted tougher combat",
    modrinthSlug: "lenders-cataclysm"
  },
  {
    id: "open-parties-claims",
    name: "Open Parties and Claims",
    summary: "Claim your land so mobs and friends can't wreck it, and form parties.",
    curatedTags: { coop: 1, building: 0.3 },
    reasonTemplate: "you play with friends",
    modrinthSlug: "open-parties-and-claims"
  },
  {
    id: "sodium-extra",
    name: "Sodium Extra",
    summary: "Extra video-setting toggles on top of Sodium for fine performance tuning.",
    curatedTags: { performance: 0.7, "low-end": 0.7, interface: 0.4 },
    reasonTemplate: "you wanted more performance control",
    modrinthSlug: "sodium-extra"
  }
];
